"""Generates blind_report_ANONYMOUS.md from the frozen CSVs. No labels are read."""
import csv, sys
from collections import defaultdict
from pathlib import Path
import numpy as np
sys.path.insert(0, str(Path(__file__).parent))
import qc_common as q

R = lambda n: list(csv.DictReader(open(q.AUDIT / n)))
F = lambda r, k: (float(r[k]) if r[k] not in ("", "nan", "None") else float("nan"))


def main():
    integ = {r["scode"]: r for r in R("blind_integrity.csv")}
    met = {r["scode"]: r for r in R("blind_metrics.csv")}
    rank = {r["scode"]: r for r in R("ranking_sensitivity.csv")}
    focal = R("blind_focal_load.csv")
    anom = R("blind_anomalies.csv")
    minp = R("blind_min_probes.csv")
    prec = R("blind_precision.csv")
    S = q.scodes()

    fconf = defaultdict(list); fweak = defaultdict(list)
    for r in focal:
        (fconf if r["verdict"] == "FOCAL_CONFIRMED" else fweak)[r["scode"]].append(r)

    poptrav = defaultdict(list)
    for r in minp:
        poptrav[(r["zone"], r["direction"])].append(F(r, "directional_travel"))
    minlow = defaultdict(list)
    for r in minp:
        if F(r, "directional_travel") < 0.5 * np.median(poptrav[(r["zone"], r["direction"])]):
            minlow[r["scode"]].append(r)

    capped = [s for s in S if F(met[s], "max_load") <= 600]
    popmax = np.median([F(met[s], "max_tps") for s in S])

    # ---------------- tier assignment (frozen criteria, applied mechanically) ----
    tier, why = {}, {}
    for s in S:
        cap = s in capped
        nconf = len(fconf[s]); nweak = len(fweak[s]); nlow = len(minlow[s])
        asym = F(met[s], "min_dir_asym")
        notes = []
        if nweak: notes.append(f"{nweak} single-bin focal load flag(s)")
        if nlow: notes.append(f"{nlow} min-speed zone(s) below 50% of population")
        if F(rank[s], "hs_crossspeed") > 0 and not nconf:
            notes.append(f"{int(F(rank[s],'hs_crossspeed'))} cross-speed speed-bin flag(s), no focal load")
        if nconf and cap:
            tier[s] = "STRONG MULTI-DOMAIN SUSPECT + CONFIGURATION-CONFOUNDED"
            why[s] = ("confirmed focal load anomaly repeatable across slow+medium+transfer "
                      "in both directions, AND a 50% output cap that independently degrades "
                      "MAX speed, precision and min-speed behaviour")
        elif nconf:
            tier[s] = "STRONG MULTI-DOMAIN SUSPECT"
            why[s] = "confirmed focal load anomaly repeatable across slow+medium (frozen criterion)"
        elif cap:
            tier[s] = "INCONCLUSIVE - CONFIGURATION-CONFOUNDED"
            why[s] = ("50% output cap; every degraded metric is explainable by the cap and "
                      "no localized mechanical signature survives")
        elif notes:
            tier[s] = "CLEAN WITH MINOR NOTE"
            why[s] = "; ".join(notes)
        else:
            tier[s] = "CLEAN"
            why[s] = "no metric outside the robust population envelope"

    o = []
    A = o.append
    A("# MATDOG — Independent Blind QC Audit of 18 × Feetech ST-3215-C018")
    A("")
    A("**Anonymous report — frozen before any label was revealed.**  ")
    A("Protocol: MATDOG QC V6.1 (binary version 61), 500 Hz RAW telemetry.  ")
    A("Scope: offline, read-only. No serial port opened, no torque enabled, no register written.")
    A("")
    A("Units are identified only by S-code. The S-code is a deterministic function of the file")
    A("content (`sha256(campaign_key || file_sha256)`, ascending), so it carries no information")
    A("about label, servo ID or acquisition order.")
    A("")
    A("---")
    A("")
    A("## 1. Integrity and tooling audit (FASE A)")
    A("")
    A("### 1.1 Everything that checks out")
    A("")
    A("| Check | Result |")
    A("|---|---|")
    A("| SHA256 of all 18 RAW vs `manifest.tsv` | **18/18 match** |")
    A("| Header magic / version / sample_hz / sample_size | `MATQC01` / 61 / 500 / 27 — uniform |")
    A("| `filesize == 84 + sample_count × 27` | exact, zero remainder, 18/18 |")
    A("| `result_code` / `abort_reason` | 0 / empty, 18/18 |")
    A("| On-device FNV-1a checksum at transfer (from logs) | PASS, 18/18 |")
    A("| `t_us` strictly monotonic | 18/18, no duplicates, no overflow |")
    A("| Protocol status byte (`st.Error`) non-zero | **0 samples out of 1,301,333** |")
    A("| Servo status byte (reg 65) non-zero | 0 samples (but see 1.3) |")
    A("| `flags` byte | 0 everywhere (never written by this firmware) |")
    A("| Position outside 0..4095 | 0 samples |")
    A("| Physically impossible encoder jumps | 0 samples |")
    A("| All 11 phases present | 18/18 |")
    A("")
    A("### 1.2 Independent re-derivation of the firmware's own numbers")
    A("")
    A("Move segmentation was derived from the RAW alone (maximal runs of constant")
    A("`phase, goal_position, goal_speed, goal_acc`) and then checked 1:1 against each log's")
    A("`MEASURE_BEGIN`/`MEASURE_END` sequence.")
    A("")
    A("- **1,672 measurement moves** reconstructed; move count matches the log for **18/18** units.")
    A("- For every one of those moves, recomputing `final position`, `position range`,")
    A("  `peak |speed|`, `peak |load|` and `peak |current|` from the RAW reproduces the")
    A("  firmware-printed value **exactly — 0 mismatches in 8,360 comparisons**.")
    A("- Per-phase sample counts match the log's `PHASE n:` lines for 18/18.")
    A("")
    A("This validates both my decoder and the firmware's own reporting path.")
    A("")
    A("### 1.3 Bugs and weaknesses found (documented, not corrected)")
    A("")
    A("**B1 — `matdog_qc_unit.sh:202-204`, header fields swapped.** The inline Python assigns")
    A("`samples = vals[4]` and `sample_size = vals[5]`, but in `<8s7I48s>` `vals[4]` *is*")
    A("`sample_size` and `vals[5]` *is* `sample_count`. The wrapper consequently prints")
    A("`SAMPLES : 27` for every unit. *Impact: cosmetic only* — neither value is validated nor")
    A("written to the manifest. **Does not alter any data or any ranking.**")
    A("`matdog_qc_runner.py:191-201` unpacks correctly.")
    A("")
    A("**B2 — the hardware status register address is not backed by the installed driver.**")
    A("The firmware treats `raw[9]` (SRAM 65) as the servo hardware-error byte and *aborts QC*")
    A("if it is non-zero. The installed `SCServo` driver (`SMS_STS.h`) defines 56, 58, 60, 62,")
    A("63, 66, 69 — **but not 64, 65, 67 or 68**. Community register tables do document 65 as")
    A("\"Servo Status\", and the value read 0 in all 1.3 M samples, but *0 is also what an")
    A("unimplemented register returns*. **Consequence: the statement \"no unit reported a")
    A("hardware fault\" is not verifiable from this dataset.** The packet-level status")
    A("(`st.Error`, register-independent) *is* verified and is clean. See §10 for the read-only")
    A("check that would settle it.")
    A("")
    A("**B3 — failed feedback reads are dropped, not recorded** (`qcReadAndStore` returns before")
    A("storing). A dropout is invisible except as a hole in `t_us`. Quantified below; benign here.")
    A("")
    A("**B4 — `qcPrintPhaseSummary` reports raw min/max temperature including known-corrupt")
    A("samples**, which is why the logs show impossible ranges such as `temp=30..130`. The log's")
    A("per-phase temperature range must not be used as evidence.")
    A("")
    A("**B5 — min-probe targets chase a moving reference** (`probeTarget = current ± 64`, with")
    A("`current` re-read after each probe), so repeated probes in one direction are not against a")
    A("fixed goal. Affects interpretation only; all 18 responded on the first probe (speed 1).")
    A("")
    A("**B6 (my own, found and fixed mid-audit, recorded for transparency).** My first")
    A("segmentation also split on `dt > 15 ms`, which produced a spurious extra segment in 3 of")
    A("18 units. Cause: the firmware's thermal-confirmation path (`qcThermalGuard`, 3 × `delay(5)`")
    A("plus direct reads) injects a ~17 ms hole *inside* a move. Fixed by segmenting on the")
    A("command tuple alone. Separately, my first MAX-speed estimator used central differences over")
    A("8 ms, which quantizes to whole encoder ticks and **fabricated ~4 % direction asymmetries**")
    A("and three spurious speed clusters; replaced by span/duration over the whole cruise. Both")
    A("errors were mine, not the firmware's, and both are corrected in the numbers below.")
    A("")
    A("### 1.4 Sampling quality")
    A("")
    A("| | min | median | max |")
    A("|---|---|---|---|")
    dtm = [float(integ[s]["dt_median_us"]) for s in S]
    gb = [float(integ[s]["gaps_at_move_boundary"]) for s in S]
    mg = [float(integ[s]["midmove_gaps_gt_6ms"]) for s in S]
    ml = [float(integ[s]["midmove_lost_samples"]) for s in S]
    A(f"| inter-sample interval (µs) | {min(dtm):.0f} | {np.median(dtm):.0f} | {max(dtm):.0f} |")
    A(f"| gaps at move boundaries (printf overhead) | {min(gb):.0f} | {np.median(gb):.0f} | {max(gb):.0f} |")
    A(f"| holes *inside* a move | {min(mg):.0f} | {np.median(mg):.0f} | {max(mg):.0f} |")
    A(f"| samples lost to those holes | {min(ml):.0f} | {np.median(ml):.0f} | {max(ml):.0f} |")
    A("")
    A("Effective rate 500 Hz (median 2000 µs). Every unit has exactly one ~64 ms hole in the")
    A("2-sample PREPOSITION prime segment — that is the torque-on handshake, not a dropout. The")
    A("3 units with an extra hole are the ones that triggered a *transient* thermal confirmation.")
    A("**No unit shows a telemetry-integrity problem.**")
    A("")
    A("---")
    A("")
    A("## 2. Blind methodology and freeze proof")
    A("")
    A("1. `RAW_SHA256_BEFORE.txt` captured before any analysis.")
    A("2. `campaign_key = sha256` over the basename-sorted `(sha256, basename)` list of the 18 RAW.")
    A("3. `S-code` = rank of `sha256(campaign_key || file_sha256)`, ascending hex.")
    A("4. The loader reads bytes only; filename, path, mtime and `header.servo_id` are dropped at")
    A("   parse time and never reach a metric, a table or a plot.")
    A("5. This report is hashed into `blind_report_ANONYMOUS.sha256` **before** the mapping file is")
    A("   read back. The labelled report is a separate file.")
    A("")
    A("**Disclosed limit of the blind:** `servo_id` is inside the RAW header, and it partitions the")
    A("set into 12 distinct IDs plus 6 files sharing one ID. Anyone re-running the parser can")
    A("recover that grouping. The blind here is *procedural* (the pipeline never reads it), not")
    A("information-theoretic. Stating this is more useful than claiming a guarantee the data")
    A("cannot support.")
    A("")
    A("**Baselines are the population itself** — median/MAD over the 18, computed separately for")
    A("each (phase, direction, encoder-bin) cell so that protocol artifacts common to all units")
    A("cancel. No \"known-good\" subset was used. Every spatial conclusion was re-run with a")
    A("**leave-one-out** baseline (a unit never contributes to the population it is judged")
    A("against): identical result, same regions, same peaks.")
    A("")
    A("---")
    A("")
    A("## 3. The 18 units")
    A("")
    A("| S-code | samples | elapsed s | moves | reach | MAX tick/s | RPM | s/60° | load ceiling | tier |")
    A("|---|---|---|---|---|---|---|---|---|---|")
    for s in S:
        m = met[s]
        A(f"| {s} | {integ[s]['n_parsed']} | {integ[s]['elapsed_s']} | "
          f"{integ[s]['n_measurement_moves']} | {int(F(m,'pos_reach_min'))}–{int(F(m,'pos_reach_max'))} | "
          f"{F(m,'max_tps'):.0f} | {F(m,'max_rpm'):.1f} | {F(m,'max_s_per_60deg'):.4f} | "
          f"{int(F(m,'max_load'))} | {tier[s]} |")
    A("")
    A("---")
    A("")
    A("## 4. Confirmed focal anomalies, with RAW indices and timestamps")
    A("")
    A("Detector: mean `Present Load` excess over the population **at the same 16-tick encoder")
    A("position**, requiring ≥4 independent traversals. Threshold = **p99.5 of the pooled")
    A("population distribution of that statistic (15.1 load units ≈ 6.1 robust SD)** — derived")
    A("from the data, not chosen by hand. A region is CONFIRMED only if ≥3 adjacent positions")
    A("(≥48 ticks) clear it.")
    A("")
    A("| S-code | encoder range | degrees | width | passes | peak excess | mean excess | speed vs pop | verdict |")
    A("|---|---|---|---|---|---|---|---|---|")
    for r in focal:
        A(f"| {r['scode']} | {r['pos_lo']}–{r['pos_hi']} | {r['deg_lo']}°–{r['deg_hi']}° | "
          f"{r['width_ticks']} | {r['passes']} | +{r['peak_excess']} | +{r['mean_excess']} | "
          f"{r['speed_rel_pct']}% | **{r['verdict']}** |")
    A("")
    A("Only **S04** and **S16** have CONFIRMED regions. The four `FOCAL_WEAK` entries are single")
    A("16-tick bins; two of them (S02 and S05) sit at the *same* position 2016, immediately below")
    A("the 2048 slow-segment boundary, which marks them as residual common-mode rather than unit")
    A("properties. Per the frozen rule, single-bin flags are notes, not findings.")
    A("")
    for s in ("S04", "S16"):
        rows = [a for a in anom if a["scode"] == s and a["confidence"] != "REJECTED_SINGLE_BIN"]
        if not rows:
            continue
        A(f"### {s} — supporting spatial clusters (speed-led detector, independent of the load detector)")
        A("")
        A("| group | dir | encoder | RAW idx | t start–end (s) | speed | baseline | deficit | load | load base | conf |")
        A("|---|---|---|---|---|---|---|---|---|---|---|")
        for a in sorted(rows, key=lambda a: int(a["pos_lo"])):
            A(f"| {a['group']} | {a['direction']} | {a['pos_lo']}–{a['pos_hi']} | "
              f"{a['raw_idx_start']}–{a['raw_idx_end']} | "
              f"{float(a['t_start_us'])/1e6:.3f}–{float(a['t_end_us'])/1e6:.3f} | "
              f"{a['speed_tps']} | {a['baseline_tps']} | {a['deficit_pct']}% | "
              f"{a['load_med']} | {a['load_baseline']} | {a['confidence']} |")
        A("")
    A("---")
    A("")
    A("## 5. Minimum-speed probes — 8 zones × 2 directions")
    A("")
    A("Directional travel in ticks during a 900 ms observation at `GoalSpeed=1`. All 18 units")
    A("responded on the first probe, so speeds 2/4/8 were never needed (`MIN_ATTEMPTS=16`,")
    A("`MIN_RESPONSES=16` for all 18).")
    A("")
    zones = sorted({int(r["zone"]) for r in minp})
    A("| S-code | " + " | ".join(f"{z}+ / {z}−" for z in zones) + " | asym |")
    A("|---" * (len(zones) + 2) + "|")
    idx = {(r["scode"], int(r["zone"]), int(F(r, "direction"))): F(r, "directional_travel") for r in minp}
    for s in S:
        cells = []
        for z in zones:
            up = idx.get((s, z, 1), float("nan")); dn = idx.get((s, z, -1), float("nan"))
            mu = np.median(poptrav[(str(z), "1")]); md = np.median(poptrav[(str(z), "-1")])
            fu = f"**{up:.0f}**" if up < 0.5 * mu else f"{up:.0f}"
            fd = f"**{dn:.0f}**" if dn < 0.5 * md else f"{dn:.0f}"
            cells.append(f"{fu} / {fd}")
        A(f"| {s} | " + " | ".join(cells) + f" | {F(met[s],'min_dir_asym'):.1f} |")
    A("| **pop median** | " + " | ".join(
        f"{np.median(poptrav[(str(z),'1')]):.0f} / {np.median(poptrav[(str(z),'-1')]):.0f}"
        for z in zones) + " | — |")
    A("")
    A("Bold = below 50 % of the population at that zone and direction.")
    A("")
    A("- **S05 is the only systematic case**: the **+ direction collapses in 6 of 8 zones**")
    A("  (10, 15, 19, 17, 18, 11 ticks against a population of 40–41) while the − direction is")
    A("  entirely normal. Directional asymmetry 23.5 ticks vs 0.0–5.0 for every other unit.")
    A("- **S04**: 3 of 8 zones below half, same + direction bias, asymmetry 5.0.")
    A("- **S03, S07, S09, S12, S17**: one isolated low zone each. Four of the five are at the same")
    A("  zone 256 (the first zone probed after a transfer), so this is partly a protocol position")
    A("  effect. Low confidence by construction — a single probe is a note, not a defect.")
    A("- A population-wide +/− asymmetry of ~2 ticks exists in *all* units and is removed by the")
    A("  per-cell baseline.")
    A("")
    A("**Caveat that limits this section:** S04 and S05 both carry the 50 % output cap (§7).")
    A("Breaking static friction at `GoalSpeed=1` is exactly what a torque cap impairs, so their")
    A("min-speed deficits **cannot be attributed to mechanics** from this dataset.")
    A("")
    A("---")
    A("")
    A("## 6. Precision, hysteresis and MAX")
    A("")
    A("| S-code | prec MAE | max abs err | bias | hyst median | hyst max | settle ms | MAX tick/s | MAX dev from pop | MAX asym | median current | peak current |")
    A("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for s in S:
        m = met[s]
        A(f"| {s} | {F(m,'prec_mae'):.2f} | {F(m,'prec_max_abs_err'):.0f} | {F(m,'prec_bias'):+.2f} | "
          f"{F(m,'hyst_med'):.1f} | {F(m,'hyst_max'):.0f} | {F(m,'prec_settle'):.0f} | "
          f"{F(m,'max_tps'):.0f} | {100*(F(m,'max_tps')-popmax)/popmax:+.1f}% | "
          f"{F(m,'max_asym_pct'):.2f}% | {F(m,'max_cur'):.1f} | {F(m,'max_cur_peak'):.0f} |")
    A("")
    A("- Precision MAE is 2.00–2.75 ticks for 16 units and **4.50 / 4.69 for S05 / S04**.")
    A("- Directional hysteresis is 4–6 ticks for 16 units and **9.0 / 8.5 for S05 / S04**.")
    A("  At 0.088°/tick that is 0.35–0.53° for the population and 0.75–0.79° for the two.")
    A("  This is *measured directional hysteresis* — control deadband + friction + backlash")
    A("  combined — and must **not** be equated with the datasheet's ≤0.5° gear backlash.")
    A("- MAX direction asymmetry is ≤1.9 % for every unit including the two capped ones.")
    A("- Overshoot past target: **0 ticks for all 18** in every MAX and precision move.")
    A("")
    A("---")
    A("")
    A("## 7. Configuration confound (FASE E) — the single most important finding")
    A("")
    A("**S04 and S05 run at almost exactly half the population's maximum speed, and their")
    A("`Present Load` register never exceeds exactly 500 while all 16 others reach exactly 1000.**")
    A("")
    A("| | 16 units | S04 | S05 |")
    A("|---|---|---|---|")
    A(f"| MAX speed (tick/s) | {popmax:.0f} (2813–2848) | {F(met['S04'],'max_tps'):.0f} | {F(met['S05'],'max_tps'):.0f} |")
    A("| as % of population | 100 % | 53.1 % | 53.2 % |")
    A("| `max |load|` ever observed | **1000** | **500** | **500** |")
    A("| samples pinned at that ceiling | ~913–982 | 2491 | 2494 |")
    A(f"| median current at MAX (raw) | 18–24.5 | {F(met['S04'],'max_cur'):.0f} | {F(met['S05'],'max_cur'):.0f} |")
    A("| bus voltage (raw) | 110–111 | 111 | 111 |")
    A("")
    A("The ceiling is *hard* — neither unit ever produced a single sample above 500 in 1.3 M")
    A("samples, and both sat pinned at exactly 500 for ~5 s of MAX travel. Per the installed")
    A("driver, `SMS_STS_TORQUE_LIMIT_L/H = 48/49` is a 16-bit SRAM value where 1000 = 100 % of")
    A("locked-rotor torque; `Max Torque` at EEPROM 16 has the same scale. **A value of 500 in")
    A("either register reproduces every observation**: half the output ceiling, ~53 % of no-load")
    A("speed, ~⅓ of the current, worse steady-state error, longer first motion, more dwell.")
    A("")
    A("Because `Present Load` truncates at 500 rather than rescaling to 1000, the register is an")
    A("**absolute** duty scale clipped by the limit, not a percentage of the limit. That is what")
    A("makes the load-excess comparison in §4 valid across capped and uncapped units.")
    A("")
    A("**Consequence for the verdicts:** every S04/S05 metric that a torque cap would degrade —")
    A("MAX speed, precision MAE, hysteresis, min-speed travel, first-motion latency, off-target")
    A("settling — is *unusable* as evidence of mechanical damage. The one thing the cap cannot")
    A("explain is a **localized** load excess at a fixed encoder angle, because S05 carries the")
    A("identical cap and is completely flat through S04's anomalous region (load 56–60 against")
    A("S04's 76–104 at the same positions, same passes). That is the discriminator this audit")
    A("rests on for S04.")
    A("")
    A("**No configuration register is present in the RAW** (only SRAM 56..70 is captured), so the")
    A("cap cannot be confirmed from this dataset — only inferred. §10 gives the read-only check.")
    A("")
    A("---")
    A("")
    A("## 8. Telemetry artifacts (FASE B)")
    A("")
    A("| S-code | temp single-sample spikes | temp runs 2–24 | temp runs ≥25 | max clean temp | temp rise | volt spikes | volt runs ≥25 | min clean volt | load=1000 at low speed |")
    A("|---|---|---|---|---|---|---|---|---|---|")
    for s in S:
        m = met[s]
        A(f"| {s} | {int(F(m,'temp_spike_single'))} | {int(F(m,'temp_run_2_24'))} | "
          f"{int(F(m,'temp_run_ge25'))} | {int(F(m,'temp_clean_max'))} | {int(F(m,'temp_rise'))} | "
          f"{int(F(m,'volt_spike_single'))} | {int(F(m,'volt_run_ge25'))} | "
          f"{int(F(m,'volt_clean_min'))} | {int(F(m,'load_sat_lowspeed_n'))} |")
    A("")
    A("- **Temperature corruption is real, firmware-acknowledged, and present in all 18.** Logs")
    A("  show `THERMAL_CANDIDATE initial=83 → confirmations [32,32,32] → THERMAL_TRANSIENT`.")
    A("  321–734 isolated corrupt samples per unit. **Not one unit has a single run of ≥25")
    A("  consecutive anomalous samples**, and after filtering, the maximum real temperature is")
    A("  35–41 °C against a 70 °C limit. Total rise over a ~150 s run: 0–5 °C.")
    A("  No thermal finding for any unit.")
    A("- **Voltage:** at most 1 isolated spike per unit, no persistent run in any unit. Raw")
    A("  extrema down to 64 (6.4 V) are single samples during braking, never sustained; the")
    A("  firmware's own 25/50-sample persistence guards never fired.")
    A("- **`load = 1000` is never a stall here.** It occurs only in the MAX phases, concurrent")
    A("  with ~2820–2850 tick/s. Samples with load saturated *and* speed below 100 tick/s:")
    A("  **0 in all 18 units**.")
    A("- Encoder and `PresentSpeed` agree: median ratio 1.000 across slow/medium/transfer/MAX,")
    A("  confirming `PresentSpeed` LSB = 1 tick/s and giving two independent motion channels.")
    A("")
    A("---")
    A("")
    A("## 9. Robust outlier table and ranking stability (FASE D)")
    A("")
    A("Features, weights and sensitivity are in `ranking_sensitivity.csv`. Four weightings were")
    A("run: spatial-led, uniform, precision-led, and mechanical-only (which zeroes every feature")
    A("a torque cap would move).")
    A("")
    A("| S-code | cross-speed bins | focal width | focal peak | min zones <50% | min asym | prec MAE | hyst | off-target | MAX deficit | Borda | rank spread | stable |")
    A("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in sorted(rank.values(), key=lambda r: int(r["rank_borda"])):
        A(f"| {r['scode']} | {F(r,'hs_crossspeed'):.0f} | {F(r,'focal_width'):.0f} | "
          f"{F(r,'focal_peak'):.0f} | {F(r,'min_zones_lt50'):.0f} | {F(r,'min_dir_asym'):.1f} | "
          f"{F(r,'prec_mae'):.2f} | {F(r,'hyst_med'):.1f} | {F(r,'med_offtarget_n'):.0f} | "
          f"{F(r,'max_tps_deficit'):.1f}% | {r['rank_borda']} | {r['rank_spread']} | "
          f"{'yes' if r['rank_stable']=='True' else 'no'} |")
    A("")
    A("Kendall τ between weightings: +0.88 to +0.96 among the three that include cap-sensitive")
    A("features, and +0.52 to +0.53 against the mechanical-only view — which is the point of")
    A("running it: **the ordering below the top 3 is driven by the cap features, not by mechanics.**")
    A("")
    A("**Stability statement, stated plainly:** only the top three positions are meaningful.")
    A("S04, S05 and S16 occupy ranks 1–3 under *every* weighting. Ranks 4–18 all have composite")
    A("scores ≤0.23 on a scale where S04 scores 2.5–3.1; their ordering changes with the weights")
    A("(spread up to 10 places) and **should not be read as a quality ordering**. Those 15 units")
    A("are statistically indistinguishable from one another.")
    A("")
    A("---")
    A("")
    A("## 10. Read-only checks still required")
    A("")
    A("None of these were performed. Each needs explicit authorization; all are pure reads.")
    A("")
    A("**Priority 1 — settle the configuration confound on S04 and S05.** Read and compare across")
    A("all 18 (addresses from the installed `SCServo/SMS_STS.h` where defined, otherwise from the")
    A("register table and to be verified on-device):")
    A("")
    A("| addr | register | why |")
    A("|---|---|---|")
    A("| 48–49 | Torque Limit (SRAM, 16-bit, 0–1000) | **the prime suspect** — 500 here explains everything |")
    A("| 16 | Max Torque (EEPROM, 0–1000) | same scale, applied at power-up |")
    A("| 21 / 22 / 23 | P / D / I | steady-state error and hysteresis |")
    A("| 24 | Minimum startup force / punch | first-motion latency, min-speed travel |")
    A("| 26 / 27 | CW / CCW dead zone | directional hysteresis, min-speed asymmetry (S05) |")
    A("| 28 | Protection current | protection behaviour |")
    A("| 34 / 35 / 36 | Protection torque / time / overload torque | protection behaviour |")
    A("| 33 | Mode | must be 0; firmware already gates on this |")
    A("| 55 | Lock | whether EEPROM was left unlocked |")
    A("| 31–32 | Position offset | affects the *absolute* angle of the §4 regions |")
    A("")
    A("**Priority 2 — resolve B2.** Read registers 64, 65, 67, 68 on a unit while deliberately")
    A("provoking a benign, self-clearing condition (e.g. read during a normal overload the")
    A("firmware already tolerates) to establish whether 65 is really the status byte. Until then,")
    A("QC's hardware-fault channel is unproven.")
    A("")
    A("**Priority 3 — characterize registers 67–68.** They are not constant (256 and 16 distinct")
    A("values in every unit, consistent with a 12-bit quantity) and are undocumented in the")
    A("installed driver. They were not used in this audit.")
    A("")
    A("**Priority 4 — re-run S04 after clearing the cap.** If Torque Limit / Max Torque is indeed")
    A("500, restoring 1000 and repeating QC is the only way to separate S04's focal anomaly from")
    A("its reduced torque headroom. That is a *write*, so it needs its own authorization.")
    A("")
    A("---")
    A("")
    A("## 11. Feetech official cross-check (FASE F)")
    A("")
    A("Source: **SHENZHEN FEETECH RC MODEL CO., LTD — \"ST-3215-C018 PRODUCT SPECIFICATION\",")
    A("Edition A/0, dated 2023-07-20** (§5 Electrical, §6 Mechanical, §7 Control).")
    A("")
    A("| Spec | Official | Measured here | Assessment |")
    A("|---|---|---|---|")
    A("| Operating voltage | 12 V (range 4–14 V) | 11.0–11.1 V measured | in range, below nominal |")
    A("| No-load speed ±10 % | 0.222 s/60° = 45 RPM @12 V | 41.2–41.7 RPM @~11.05 V | voltage-scaled expectation 41.4 RPM — **population is exactly at spec** |")
    A("| No-load running current ±10 % | 180 mA | median 117–159 mA, peak 208–273 mA @ MAX | consistent |")
    A("| Idle current | 30 mA | ~6.5 mA at 1.8 RPM (1 LSB) | below idle spec; see note |")
    A("| Rated / stall current | 900 mA / 2.7 A | never approached (max 273 mA) | no unit loaded near rating |")
    A("| Encoder | 12-bit magnetic, 0.088°/pulse | 4096 ticks/rev confirmed | matches |")
    A("| Backlash | ≤0.5° | not separately measurable | see §6 caveat |")
    A("| Over-hot protection | >70 °C torque off | max clean temp 41 °C | never approached |")
    A("| Over-current protection | >2 A for 2 s | never approached | — |")
    A("| Over-load protection | >80 % stall for 2 s | load 1000 reached at full speed only | not a stall |")
    A("")
    A("Firmware constants are all corroborated: `6.5 mA/raw`, `no_load≈28 raw` (=182 mA),")
    A("`rated≈139` (=904 mA), `overcurrent≈308` (=2.00 A), `stall≈416` (=2.70 A), overload 80 %.")
    A("")
    A("**Discrepancy to record:** the installed `SCServo` driver documents neither register 65 nor")
    A("67/68, while community register tables document 65 as \"Servo Status\". The official")
    A("specification sheet above is a product datasheet and contains no memory table at all, so it")
    A("cannot arbitrate. Reported as an open discrepancy rather than resolved by preference.")
    A("")
    A("**Resolution of a concern I raised during planning:** I flagged the measured currents as")
    A("implausibly low. Against the official 180 mA no-load figure they are correct — 117–159 mA")
    A("median at 92 % of nominal voltage. The real limitation is *resolution*: at 6.5 mA/LSB, slow")
    A("moves read 1–3 LSB, so **current is not a usable diagnostic channel below MAX speed**.")
    A("`Present Load` is, and that is what the §4 detector uses.")
    A("")
    A("---")
    A("")
    A("## 12. Tiers")
    A("")
    for t in ("STRONG MULTI-DOMAIN SUSPECT + CONFIGURATION-CONFOUNDED",
              "STRONG MULTI-DOMAIN SUSPECT",
              "INCONCLUSIVE - CONFIGURATION-CONFOUNDED",
              "MILD/LOCALIZED ANOMALY",
              "CLEAN WITH MINOR NOTE", "CLEAN"):
        us = [s for s in S if tier[s] == t]
        if not us:
            continue
        A(f"### {t} — {len(us)} unit(s)")
        A("")
        for s in us:
            A(f"- **{s}** — {why[s]}")
        A("")
    A("---")
    A("")
    A("## 13. If 12 units must be chosen")
    A("")
    A("**High-confidence exclusions (3):**")
    A("")
    A("- **S04** — confirmed focal load anomaly at encoder 2144–2271 (188.4°–199.7°), peak +31")
    A("  load units over population, present in all 6 independent traversals in both directions,")
    A("  *plus* a 50 % output cap. Exclude on either ground.")
    A("- **S05** — 50 % output cap, and the only unit with a systematic directional min-speed")
    A("  collapse (6 of 8 zones in the + direction). Exclude, but note the cause may be entirely")
    A("  configuration; it is a candidate for recovery after a register check.")
    A("- **S16** — confirmed focal load anomaly at encoder 2560–2751 (225°–242°), peak +42 load")
    A("  units, all 6 traversals. No configuration confound, so this one is *clean mechanical")
    A("  evidence*. Its speed, precision, MAX and telemetry are all population-normal, so the")
    A("  practical severity is lower than S04's — but the localization is the most certain of the three.")
    A("")
    A("**That leaves 15 candidates for 12 slots, and the data does not support choosing among")
    A("them.** The 15 are statistically indistinguishable: composite scores ≤0.23 versus 2.5–3.1")
    A("for the excluded three, and their rank order is unstable under reweighting (spread up to 10")
    A("places). Stating a \"best 12\" would be inventing precision that is not in the measurements.")
    A("")
    A("If 12 must be picked, the only defensible tie-break is to prefer units with no minor note")
    A("at all, then accept that the remainder is arbitrary:")
    A("")
    noteless = [s for s in S if tier[s] == "CLEAN"]
    noted = [s for s in S if tier[s] == "CLEAN WITH MINOR NOTE"]
    A(f"- **No note at all ({len(noteless)}):** {', '.join(noteless)}")
    A(f"- **Minor note only ({len(noted)}):** " + "; ".join(f"{s} ({why[s]})" for s in noted))
    A("")
    if len(noteless) >= 12:
        A(f"Twelve can be taken from the note-free group alone. The choice among the")
        A(f"{len(noteless)} is arbitrary on this evidence — any 12 of them are equivalent.")
    else:
        A(f"Only {len(noteless)} units are note-free, so {12-len(noteless)} must come from the")
        A("minor-note group. Those notes are single isolated observations and, per the frozen")
        A("criteria, carry low confidence — they are tie-breakers, not defects.")
    A("")
    A("**Confidence:** exclusion of S04 and S16 on focal-anomaly grounds — **high** (survives a")
    A("leave-one-out baseline, 6 independent passes each, ≥6 robust SD, two independent detectors).")
    A("Exclusion of S05 — **high as a screening decision, low as a mechanical diagnosis**: the cap")
    A("alone may explain all of it. Inclusion of any specific 12 of the remaining 15 — **low**,")
    A("because the units are indistinguishable, not because they are doubtful.")
    A("")
    A("---")
    A("")
    A("## 14. Results that contradict expectations, stated explicitly")
    A("")
    A("- `QC_EXECUTION: COMPLETE`, `CHECKSUM: PASS`, `PERFORMANCE_EVENTS: 0`,")
    A("  `PROTECTIVE_STOPS: 0` for **all 18** — and yet three units carry real, repeatable")
    A("  anomalies. The pass flags describe the *test*, not the servo, exactly as the protocol says.")
    A("- The two slowest units (S04, S05, at 53 % of population speed) are **not** the two with the")
    A("  clearest mechanical evidence. S16 runs at full population speed and has the largest focal")
    A("  load anomaly in the campaign.")
    A("- Conversely S05, which looks bad on five separate summary metrics, has **no** localized")
    A("  mechanical signature at all once its co-capped twin S04 is used as the control.")
    A("- No unit had a restricted travel envelope; all 18 reached 1–3 at the bottom and 4090–4095")
    A("  at the top.")
    A("- Two of my own analysis methods produced artifacts that would have created false findings")
    A("  (a fabricated 4 % MAX direction asymmetry across the whole population, and 3 spurious")
    A("  move splits). Both are documented in §1.3 rather than quietly corrected.")
    A("")

    (q.AUDIT / "blind_report_ANONYMOUS.md").write_text("\n".join(o) + "\n")
    print(f"wrote blind_report_ANONYMOUS.md ({len(o)} lines)")
    for t in sorted(set(tier.values())):
        print(f"  {t}: {', '.join(s for s in S if tier[s]==t)}")


if __name__ == "__main__":
    main()
