#!/usr/bin/env python3
"""Export canonical foot-contact geometry and the pinned C4 stand definition.
Uses existing loaders/binding validation; does not implement Python kinematics.
"""
import argparse
import json
import math
from pathlib import Path

from matdog_foot_contact import load_foot_contact_model, CONFIG_RELATIVE_PATH
from matdog_leg_contact import validate_canonical_foot_joint_bindings
from matdog_motion_geometry_export import ROOT, LEGS, require, render
from matdog_urdf_fk import canonical_urdf_path, sha256_file, load_urdf_joints

C4A = Path('09_Logs/Validation_Reports/2026-07-08_175245_C4A_offline_safe_stand_candidate.json')
C4C = Path('09_Logs/Validation_Reports/C4_rest_to_stand_trajectory/2026-07-08_190405_C4C_contact_locked_rest_to_stand_trajectory.json')
DEST = Path('05_Firmware/MATDOG_Controller/src/motion')


def vec(values):
    return '{' + ', '.join(repr(float(v)) for v in values) + '}'


def render_contact(root=ROOT):
    render(canonical_urdf_path(root))  # prove the G1 reduction assumptions too
    validate_canonical_foot_joint_bindings(root)
    m = load_foot_contact_model(root)
    values = (*m.cylinder_center_in_foot_link_m, *m.cylinder_axis_in_foot_link_unit,
              m.cylinder_radius_m, m.total_tread_width_m, m.end_fillet_radius_m,
              m.central_rigid_support_width_m, m.nominal_strip_max_axis_tilt_from_ground_rad)
    require(all(math.isfinite(v) for v in values), 'nonfinite contact geometry')
    require(m.cylinder_axis_in_foot_link_unit == (0, 1, 0) and
            m.cylinder_center_in_foot_link_m == (0, 0, m.cylinder_radius_m),
            'analytic contact IK requires centered Y cylinder at Z=radius')
    joints = load_urdf_joints(canonical_urdf_path(root))
    for leg in LEGS:
        hip = joints[f'{leg}_hip_joint']
        require(-math.pi/2 < hip.lower_limit_rad < hip.upper_limit_rad < math.pi/2,
                'contact radial reduction requires cos(hip)>0')
        foot = joints[f'{leg}_foot_joint'].origin_xyz
        a = -joints[f'{leg}_lower_leg_joint'].origin_xyz[2]
        b = math.hypot(foot[0], foot[2] + m.cylinder_radius_m)
        require(1e-6 < b < 1 and abs(a-b) > 1e-6, 'degenerate contact planar geometry')
    return ('// Generated by matdog_contact_stand_export.py; DO NOT EDIT.\n'
            f'// Source: {CONFIG_RELATIVE_PATH}\n'
            '#ifndef MATDOG_MOTION_FOOT_CONTACT_DATA_H\n#define MATDOG_MOTION_FOOT_CONTACT_DATA_H\n'
            '#include "FootContact.h"\nnamespace matdog { namespace motion { namespace generated {\n'
            f'constexpr char kContactSha256[] = "{sha256_file(root / CONFIG_RELATIVE_PATH)}";\n'
            'constexpr FootContactModel kContact = {\n  ' + vec(values[:3]) + ', ' + vec(values[3:6]) + ',\n  ' +
            ', '.join(repr(v) for v in values[6:]) + '\n};\n} } }\n#endif\n')


def render_stand(root=ROOT):
    render_contact(root)
    a, c = (json.loads((root / p).read_text()) for p in (C4A, C4C))
    frames = c['frames']
    policy = c['trajectory_policy']
    low, high = policy['start_body_z_m'], policy['final_body_z_m']
    require(math.isfinite(low) and math.isfinite(high) and 0 < low < high,
            'invalid body heights')
    require(len(frames) == 51 and c['metrics']['all_samples_safe'], 'unvalidated C4-C')
    require(a['body_pose']['translation_world_m'] == [0, 0, high] and
            a['body_pose']['base_link_parallel_to_ground'], 'unexpected C4-A body pose')
    require(a['body_pose']['rotation_world_from_base'] == [[1,0,0],[0,1,0],[0,0,1]] and
            all(a['body_pose'][key] == 0 for key in ('roll_rad','pitch_rad','yaw_rad')),
            'unsupported C4-A body rotation')
    require(policy['foot_contact_world_z_m'] == 0 and policy['body_parallel_to_ground'],
            'unsupported C4-C stance')
    contacts, seeds = [], []
    joints = load_urdf_joints(canonical_urdf_path(root))
    for leg in LEGS:
        record = a['legs'][leg]
        contact = record['target_contact_reference_world_m']
        seed = [record['joint_positions_rad'][f'{leg}_{s}_joint']
                for s in ('hip', 'upper_leg', 'lower_leg')]
        require(all(math.isfinite(v) for v in contact + seed) and contact[2] == 0,
                'invalid stand reference')
        require(record['support_mode'] == 'NOMINAL_STRIP_CONTACT', 'non-nominal stand')
        for value, suffix in zip(seed, ('hip', 'upper_leg', 'lower_leg')):
            joint = joints[f'{leg}_{suffix}_joint']
            require(joint.lower_limit_rad <= value <= joint.upper_limit_rad, 'stand seed outside limits')
        contacts.append(vec(contact)); seeds.append(vec(seed))
    for i, frame in enumerate(frames):
        require(frame['body_pose']['translation_world_m'][:2] == [0, 0] and
                all(frame['body_pose'][key] == 0 for key in ('roll_rad','pitch_rad','yaw_rad')),
                'unsupported C4-C body transform')
        require(frame['evaluation']['safe'] and frame['body_pose']['base_link_parallel_to_ground'],
                'unsafe archived frame')
        require(abs(frame['body_pose']['translation_world_m'][2] -
                    (low+(high-low)*i/(len(frames)-1))) < 1e-12, 'nonlinear body-height sequence')
        for leg in LEGS:
            require(frame['legs'][leg]['target_contact_reference_world_m'] ==
                    a['legs'][leg]['target_contact_reference_world_m'], 'unlocked C4 footprint')
    return ('// Generated by matdog_contact_stand_export.py; DO NOT EDIT.\n'
            f'// Source: {C4A}\n// Source: {C4C}\n'
            '#ifndef MATDOG_MOTION_STAND_REFERENCE_DATA_H\n#define MATDOG_MOTION_STAND_REFERENCE_DATA_H\n'
            '#include "StandTrajectory.h"\nnamespace matdog { namespace motion { namespace generated {\n'
            f'constexpr char kC4ASha256[] = "{sha256_file(root/C4A)}";\n'
            f'constexpr char kC4CSha256[] = "{sha256_file(root/C4C)}";\n'
            'constexpr StandDefinition kStand = {\n  {' + ', '.join(contacts) + '},\n  {' +
            ', '.join(seeds) + '},\n  ' + f'{low!r}, {high!r}, {len(frames)}' + '\n};\n} } }\n#endif\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in [('FootContactData.h', render_contact()),
                          ('StandReferenceData.h', render_stand())]:
        path = ROOT / DEST / name
        if args.check:
            require(path.is_file() and path.read_text() == content, f'stale {name}')
        else:
            path.write_text(content)
    print('CONTACT_STAND_GEOMETRY = PASS')


if __name__ == '__main__':
    main()
