#!/usr/bin/env python3
"""Export a verified subset of Geometry V5's URDF model for pure C++ motion.

This is a small model exporter, not a second geometry compiler. It uses V5
for topology/parsing and exports no actuator metadata. Unsupported topology
or transforms fail closed: the analytic solver must be reviewed first.
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "06_Software/Matdog_Core/calibration"))
from matdog_geometry_model_v5 import load_robot_geometry_model
from matdog_urdf_fk import canonical_urdf_path, sha256_file, CANONICAL_URDF_RELATIVE_PATH

OUTPUT = ROOT / "05_Firmware/MATDOG_Controller/src/motion/LegGeometryData.h"
LEGS = ("lf", "rf", "rh", "lh")


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def render(urdf_path: Path) -> str:
    model = load_robot_geometry_model(urdf_path)
    require(model.root_link == "base_link", "expected base_link root")
    rows = []
    for leg in LEGS:
        names = tuple(f"{leg}_{suffix}_joint" for suffix in
                      ("hip", "upper_leg", "lower_leg", "foot"))
        require(model.joint_chain_by_link[f"{leg}_foot_link"] == names,
                f"{leg}: unsupported chain")
        joints = [model.joints[name] for name in names]
        require([j.joint_type for j in joints] == ["revolute"] * 3 + ["fixed"],
                f"{leg}: unsupported joint types")
        require(all(j.origin_rpy == (0.0, 0.0, 0.0) for j in joints),
                f"{leg}: nonzero origin rotation requires solver review")
        require([j.axis_xyz for j in joints[:3]] ==
                [(1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 1.0, 0.0)],
                f"{leg}: expected X/Y/Y axes")
        _, upper, lower, foot = (j.origin_xyz for j in joints)
        require(upper[0] == upper[2] == lower[0] == lower[1] == 0.0,
                f"{leg}: unsupported upper/lower offsets")
        length = -lower[2]
        distal = math.hypot(foot[0], foot[2])
        lateral = upper[1] + foot[1]
        require(1e-6 < length < 1.0 and 1e-6 < distal < 1.0 and
                abs(length - distal) > 1e-6 and 1e-6 < abs(lateral) < 1.0,
                f"{leg}: degenerate or unsupported dimensions")
        limits = [(j.lower_limit_rad, j.upper_limit_rad) for j in joints[:3]]
        require(all(lo is not None and hi is not None and
                    math.isfinite(lo) and math.isfinite(hi) and
                    -math.pi < lo < 0.0 < hi < math.pi for lo, hi in limits),
                f"{leg}: limits must contain zero strictly inside (-pi, pi)")
        def vec(values):
            return "{" + ", ".join(format(v, ".17g") for v in values) + "}"
        origins = ", ".join(vec(j.origin_xyz) for j in joints)
        rows.append(f"  // {leg.upper()}: " + " -> ".join(names) + "\n" +
                    "  {" + origins + ", {" + ", ".join(vec(v) for v in limits) + "}},")
    return ("// Generated by matdog_motion_geometry_export.py; DO NOT EDIT.\n"
            f"// Source: {CANONICAL_URDF_RELATIVE_PATH.as_posix()}\n"
            "// Geometry V5 topology, exact URDF origins and limits; X/Y/Y axes, zero RPY.\n"
            "#ifndef MATDOG_MOTION_LEG_GEOMETRY_DATA_H\n"
            "#define MATDOG_MOTION_LEG_GEOMETRY_DATA_H\n"
            '#include "LegKinematics.h"\n'
            "namespace matdog { namespace motion { namespace generated {\n"
            f'constexpr char kUrdfSha256[] = "{sha256_file(urdf_path)}";\n'
            "constexpr LegModel kLegs[4] = {\n" + "\n".join(rows) +
            "\n};\n} } }\n#endif\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(canonical_urdf_path(ROOT))
    if args.check:
        require(OUTPUT.is_file() and OUTPUT.read_text() == content,
                "motion geometry is stale; regenerate and review")
        print("MOTION_GEOMETRY = PASS (Geometry V5 / live URDF)")
    else:
        OUTPUT.write_text(content)


if __name__ == "__main__":
    main()
