"""Standard-library-only semantic pose exporter and canonical freshness gate."""
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
DATA=ROOT/'09_Logs/Validation_Reports/G35_Pose_Audit/pose_library.json'
TARGET=ROOT/'05_Firmware/MATDOG_Controller/src/motion/PoseReferenceData.h'
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def render(data):
 def number(x):return format(x,'.17g')
 def vec(v):return '{'+','.join(number(x) for x in v)+'}'
 lines=['// Generated by pose_audit/pose_export.py. Static geometry evidence only.', '#ifndef MATDOG_MOTION_POSE_REFERENCE_DATA_H','#define MATDOG_MOTION_POSE_REFERENCE_DATA_H','#include "PoseSupport.h"','namespace matdog { namespace motion { namespace generated {', 'inline constexpr char kPoseSourceDigest[] = "'+digest(DATA)+'";','inline constexpr SemanticPose kPoses[] = {']
 for r in data['poses']:
  if not r['embedded_target']:continue
  if r['evidence']!='VALIDATED_STATIC' or not r['valid']:raise ValueError('Only validated MATDOG geometry may enter embedded records')
  b=r['body'];body='{'+vec([b[i][3] for i in range(3)])+',{'+','.join(vec(row[:3]) for row in b[:3])+'}}'
  q=r['q'];frame='{{'+','.join(vec(q[i:i+3]) for i in range(0,12,3))+'},0,true}'
  mask=sum(1<<('lf','rf','rh','lh').index(l) for l in r['active_feet']);base='true' if r['base_contact'] else 'false'
  lines.append('  {"'+r['name']+'",'+body+','+frame+', {PoseSupportRegime::'+r['regime']+',{'+base+','+str(mask)+'}},PoseEvidence::VALIDATED_STATIC,'+vec(r['com_world_m'])+','+number(r['support_margin_m'])+','+number(r['joint_margin_rad'])+'},')
 lines+=['};','inline constexpr uint8_t kPoseCount = sizeof(kPoses)/sizeof(kPoses[0]);','} } }','#endif','']
 return '\n'.join(lines)
def check_sources(data):
 for name,expected in data['provenance']['canonical_sources'].items():
  if digest(ROOT/name)!=expected:raise ValueError('Stale canonical pose data: '+name)
 for name,expected in data['provenance']['inputs'].items():
  if digest(DATA.parent/name)!=expected:raise ValueError('Stale pose search input: '+name)
 for name,key in [('pose_library.py','generator_sha256'),('model.py','model_sha256'),('diagnostics.py','diagnostics_sha256')]:
  if digest(Path(__file__).with_name(name))!=data['provenance'][key]:raise ValueError('Stale pose generator: '+name)
def main():
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();data=json.loads(DATA.read_text());check_sources(data);result=render(data)
 if a.check:
  if TARGET.read_text()!=result:raise ValueError('Stale PoseReferenceData.h')
 else:TARGET.write_text(result)
 print('POSE_DATA_FRESHNESS = PASS')
if __name__=='__main__':main()
