#ifndef MATDOG_NETWORK_PORTAL_PAGE_H
#define MATDOG_NETWORK_PORTAL_PAGE_H
namespace matdog { namespace network {
static constexpr char kPortalPage[]=R"MATDOG(<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MATDOG · rete locale</title><style>
:root{color-scheme:dark;font:16px system-ui;background:#111923;color:#e6edf5}body{max-width:960px;margin:auto;padding:20px}header{display:flex;justify-content:space-between;align-items:center}h1{font-size:24px;color:#5cd6cf}nav{display:flex;flex-wrap:wrap;gap:8px;margin:20px 0}button{padding:10px 16px;background:#20384a;color:white;border:1px solid #456075;border-radius:8px;cursor:pointer}button:hover{background:#2a5663}section{background:#1a2633;padding:18px;border-radius:12px;margin:12px 0}label{display:block;margin:12px 0}input,select{display:block;box-sizing:border-box;width:100%;padding:10px;background:#111923;color:#fff;border:1px solid #456075;border-radius:6px}input[type=checkbox]{width:auto;display:inline}fieldset{border:1px solid #456075;margin:15px 0;border-radius:8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:18px}.muted{color:#afc1d0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}#message{position:sticky;top:8px;background:#234e56;padding:12px;border-radius:8px}a{color:#5cd6cf}[hidden]{display:none}</style>
<header><h1>MATDOG</h1><span>Gestione locale</span></header><p class="muted">Firmware offline candidate. Le prove hardware sono ancora da eseguire.</p><div id="message" role="status">Connessione allo stato del dispositivo…</div><nav><button data-page="dashboard">Dashboard</button><button data-page="wifi">Wi-Fi</button><button data-page="ap">Access Point</button><button data-page="performance">Performance</button><button data-page="ota">OTA</button><button data-page="diagnostics">Diagnostics</button></nav>
<section id="login"><h2>Accesso proprietario</h2><p>Le modifiche sono disponibili collegandosi all'AP protetto MATDOG, su <a href="http://192.168.4.1">192.168.4.1</a>. Usa il token amministratore univoco impostato via USB. L'HTTP locale è protetto dal collegamento WPA2; altri client che conoscono la password AP condividono questo confine di fiducia.</p><form id="loginForm"><label>Token amministratore (64 cifre esadecimali)<input type="password" name="token" minlength="64" maxlength="64" autocomplete="off" required></label><button>Accedi</button></form></section>
<section id="dashboard"><h2>Dashboard</h2><pre id="overview"></pre><p id="staLink"></p></section>
<section id="wifi" hidden><h2>Wi-Fi</h2><p>Due profili, una sola associazione. Password vuota conserva la password della stessa rete. Quando cambi SSID, inserisci la nuova password. La prova richiede l'AP disponibile: il precedente profilo ACTIVE rimane valido fino a associazione e IP riusciti.</p><button id="scan">Scansiona</button><pre id="scanResults"></pre><form id="wifiForm"><div class="grid" id="profiles"></div><label>Profilo da provare<select name="test_profile"><option value="0">Primary</option><option value="1">Secondary</option></select></label><button>Prova e salva</button></form></section>
<section id="ap" hidden><h2>Access Point</h2><p>Una radio condivisa con la STA: il canale può cambiare durante l'associazione. Recovery AP resta disponibile se manca una STA. Cambio delle credenziali AP richiede una connessione STA attiva. Non viene spento durante prove o con client collegati.</p><button id="apOn">Attiva AP</button><button id="apOff">Disattiva AP</button><form id="apForm"><label>Nome AP (vuoto: MAC dispositivo)<input name="ap_name" maxlength="32"></label><label>Nuova password WPA2 (vuoto: conserva)<input name="ap_password" type="password" maxlength="63" autocomplete="new-password"></label><label>Timeout in millisecondi<input name="ap_timeout_ms" type="number" min="60000" max="3600000" value="900000"></label><label>Disponibilità permanente<select name="ap_always"><option value="0">Solo recovery / on demand</option><option value="1">Sempre disponibile</option></select></label><input name="test_profile" type="hidden" value="0"><button>Prova e salva</button></form></section>
<section id="performance" hidden><h2>Performance</h2><p>Roaming disattivato di default. Scansioni sospese in calibrazione, RUN e OTA. Il modem sleep resta OFF perché HWCDC non prova l'apertura di una sessione USB.</p><form id="performanceForm"><label>Roaming<select name="roam_enabled"><option value="0">Disattivo</option><option value="1">Attivo</option></select></label><label>Soglia RSSI<input name="roam_threshold" type="number" min="-95" max="-50" value="-80"></label><label>Isteresi dB<input name="roam_hysteresis" type="number" min="3" max="30" value="8"></label><label>Intervallo scansioni ms<input name="scan_interval_ms" type="number" min="30000" max="3600000" value="60000"></label><label>Dwell ms<input name="roam_dwell_ms" type="number" min="60000" max="3600000" value="120000"></label><label>Larghezza banda STA<select name="bandwidth_mhz"><option value="20">HT20</option><option value="40">HT40 · da validare sul router</option></select></label><input name="test_profile" type="hidden" value="0"><button>Prova e salva</button></form></section>
<section id="ota" hidden><h2>OTA</h2><p>Il candidato mantiene ingest OFF. L'upload usa esclusivamente TLS con identità verificata e HMAC, dopo i gate di sicurezza. Il riavvio remoto resta bloccato in questa fase; nessun aggiornamento è attivato da questa pagina.</p><pre id="firmware"></pre></section>
<section id="diagnostics" hidden><h2>Diagnostics</h2><pre id="details"></pre></section>
<script>
let csrf='',editing=false;const message=document.querySelector('#message');const show=t=>message.textContent=t;
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{['dashboard','wifi','ap','performance','ota','diagnostics'].forEach(p=>document.getElementById(p).hidden=p!==b.dataset.page)});
for(let i=0;i<2;i++){const f=document.createElement('fieldset');f.innerHTML='<legend>'+(['Primary','Secondary'][i])+'</legend>'+[['ssid','SSID','text'],['password','Password (write only)','password'],['enabled','Attivo: 1 oppure 0','number'],['dhcp','DHCP: 1 oppure 0','number'],['ip','IP statico','text'],['mask','Subnet mask','text'],['gateway','Gateway','text'],['dns','DNS','text']].map(([key,label,type])=>'<label>'+label+'<input name="p'+i+'_'+key+'" type="'+type+'" '+(key==='password'?'autocomplete="new-password" maxlength="63"':key==='ssid'?'maxlength="32"':'')+' value="'+(['enabled','dhcp'].includes(key)?(key==='dhcp'?'1':'0'):['ip','mask','gateway','dns'].includes(key)?'0.0.0.0':'')+'"></label>').join('');document.querySelector('#profiles').append(f)}
async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Csrf-Token':csrf},body});const t=await r.text();if(!r.ok)throw Error(t);return t}
document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const f=e.target;try{csrf=await post('/wifi/login',new URLSearchParams(new FormData(f)));show('Sessione attiva per 5 minuti');}catch(x){show(x.message)}finally{f.reset()}};
for(const id of ['wifiForm','apForm','performanceForm'])document.getElementById(id).onsubmit=async e=>{e.preventDefault();try{show(await post('/wifi/config',new URLSearchParams(new FormData(e.target))));e.target.querySelectorAll('input[type=password]').forEach(p=>p.value='')}catch(x){show(x.message)}};
document.querySelector('#scan').onclick=async()=>{try{show(await post('/wifi/scan',''))}catch(x){show(x.message)}};
for(const [id,on] of [['apOn','1'],['apOff','0']])document.getElementById(id).onclick=async()=>{try{show(await post('/wifi/ap','on='+on))}catch(x){show(x.message)}};
document.querySelectorAll('form').forEach(f=>f.addEventListener('input',()=>editing=true));
async function status(){try{const r=await fetch('/wifi/status');if(!r.ok)throw Error('Dispositivo non disponibile');const s=await r.json();document.querySelector('#overview').textContent=JSON.stringify({STA:s.connected,SSID:s.ssid,BSSID:s.bssid,IP:s.ip,RSSI:s.rssi,canale:s.channel,AP:s.ap_active,sleep:s.sleep_effective,config:s.config_phase},null,2);document.querySelector('#details').textContent=JSON.stringify(s,null,2);document.querySelector('#scanResults').textContent=JSON.stringify(s.scan,null,2);document.querySelector('#firmware').textContent='Build '+s.build_id+' · ingest '+s.ota_ingest+' · TLS '+s.tls;
const l=document.querySelector('#staLink');l.textContent=s.connected?'Indirizzo STA: http://'+s.ip:'';
for(const f of ['apForm','performanceForm'])document.getElementById(f).elements.test_profile.value=s.active_profile;
if(!editing){s.profiles.forEach((p,i)=>{for(const key of ['ssid','enabled','dhcp','ip','mask','gateway','dns'])document.querySelector('[name=p'+i+'_'+key+']').value=typeof p[key]==='boolean'?(p[key]?'1':'0'):p[key]});document.querySelector('[name=ap_name]').value=s.ap_ssid;for(const key of ['roam_enabled','roam_threshold','roam_hysteresis','scan_interval_ms','roam_dwell_ms','bandwidth_mhz','ap_timeout_ms','ap_always']){const el=document.querySelector('[name='+key+']');if(el)el.value=typeof s[key]==='boolean'?(s[key]?'1':'0'):s[key]}}
if(s.ap_reload_pending)show('AP salvato · nuove credenziali applicate quando tutti i client si scollegano');else if(s.config_busy)show('TESTING · puoi perdere brevemente il canale AP durante l’associazione');else if(s.config_error)show('Errore '+s.config_error+' · '+s.config_phase);else if(s.config_phase==='COMMITTED'||s.config_phase==='ROLLBACK')show(s.config_phase);
}catch(x){show('Connessione interrotta. Ricollegati all’AP MATDOG e riprova.')}setTimeout(status,3000)}status();
</script></html>)MATDOG";
} }
#endif
