// Generated by matdog_contact_stand_export.py; DO NOT EDIT.
// Source: 06_Software/Matdog_Core/kinematics/MATDOG_FOOT_CONTACT_GEOMETRY.yaml
#ifndef MATDOG_MOTION_FOOT_CONTACT_DATA_H
#define MATDOG_MOTION_FOOT_CONTACT_DATA_H
#include "FootContact.h"
namespace matdog { namespace motion { namespace generated {
constexpr char kContactSha256[] = "43dc72abdc132ef2492d383efe4ed12dfe2e18cf17705e69fc21f4166c4f0966";
constexpr FootContactModel kContact = {
  {0.0, 0.0, 0.0149}, {0.0, 1.0, 0.0},
  0.0149, 0.0139, 0.002, 0.0099, 0.034906585
};
} } }
#endif
