// Generated by matdog_motion_geometry_export.py; DO NOT EDIT.
// Source: 03_CAD/URDF/matt_robodog_rev00/matt_robodog_rev00.urdf
// Geometry V5 topology, exact URDF origins and limits; X/Y/Y axes, zero RPY.
#ifndef MATDOG_MOTION_LEG_GEOMETRY_DATA_H
#define MATDOG_MOTION_LEG_GEOMETRY_DATA_H
#include "LegKinematics.h"
namespace matdog { namespace motion { namespace generated {
constexpr char kUrdfSha256[] = "3890a3f0732dbed8abdc559106d7f32ee8d6e2111c8e1a06d2485bf2ffc81e59";
constexpr LegModel kLegs[4] = {
  // LF: lf_hip_joint -> lf_upper_leg_joint -> lf_lower_leg_joint -> lf_foot_joint
  {{0.1125, 0.047500000000000001, 0.0465}, {0, 0.048000000000000001, 0}, {0, 0, -0.089999999999999997}, {0.107, -0.0015, -0.0499}, {{-0.78539816339699997, 0.78539816339699997}, {-0.91629785729699997, 2.1380283336930002}, {-1.6057029118349999, 0.65449846949799995}}},
  // RF: rf_hip_joint -> rf_upper_leg_joint -> rf_lower_leg_joint -> rf_foot_joint
  {{0.1125, -0.047500000000000001, 0.0465}, {0, -0.048000000000000001, 0}, {0, 0, -0.089999999999999997}, {0.107, 0.0015, -0.0499}, {{-0.78539816339699997, 0.78539816339699997}, {-0.91629785729699997, 2.1380283336930002}, {-1.6057029118349999, 0.65449846949799995}}},
  // RH: rh_hip_joint -> rh_upper_leg_joint -> rh_lower_leg_joint -> rh_foot_joint
  {{-0.1125, -0.047500000000000001, 0.026499999999999999}, {0, -0.048000000000000001, 0}, {0, 0, -0.089999999999999997}, {0.107, 0.0015, -0.0499}, {{-0.78539816339699997, 0.78539816339699997}, {-0.91629785729699997, 2.1380283336930002}, {-1.6057029118349999, 0.65449846949799995}}},
  // LH: lh_hip_joint -> lh_upper_leg_joint -> lh_lower_leg_joint -> lh_foot_joint
  {{-0.1125, 0.047500000000000001, 0.026499999999999999}, {0, 0.048000000000000001, 0}, {0, 0, -0.089999999999999997}, {0.107, -0.0015, -0.0499}, {{-0.78539816339699997, 0.78539816339699997}, {-0.91629785729699997, 2.1380283336930002}, {-1.6057029118349999, 0.65449846949799995}}},
};
} } }
#endif
