#include "LegKinematics.h"

#include <cmath>
#include <limits>

namespace matdog {
namespace motion {
namespace {
constexpr double kPi = 3.14159265358979323846;
// Roundoff guards, not an extension of the physical workspace/URDF limits.
constexpr double kDomainEpsilon = 1e-12;
constexpr double kLimitEpsilonRad = 1e-12;

double clamp(double value, double low, double high) {
  return value < low ? low : (value > high ? high : value);
}

double norm(const Vector3& p) { return std::hypot(std::hypot(p.x, p.y), p.z); }

// The generator requires every limit interval to be strictly inside (-pi, pi).
// Hence each angle has at most one equivalent representative in that interval.
bool boundedAngle(double raw, const JointLimit& limit, double& value) {
  value = std::remainder(raw, 2.0 * kPi);
  if (value < limit.lower - kLimitEpsilonRad ||
      value > limit.upper + kLimitEpsilonRad) return false;
  value = clamp(value, limit.lower, limit.upper);
  return true;
}
}  // namespace

IkResult inverseKinematics(LegId leg, const Vector3& target,
                           const IkOptions& options) {
  IkResult result;
  const LegModel* model = legModel(leg);
  if (!model || !std::isfinite(target.x) || !std::isfinite(target.y) ||
      !std::isfinite(target.z) || !std::isfinite(options.toleranceM) ||
      options.toleranceM < 1e-12 || options.toleranceM > 1e-3) return result;
  const FkResult seedFk = forwardKinematics(leg, options.seed);
  if (seedFk.status != KinematicsStatus::OK) {
    result.status = seedFk.status;
    return result;
  }
  const Vector3 p = {target.x - model->hipOrigin.x,
                     target.y - model->hipOrigin.y,
                     target.z - model->hipOrigin.z};
  const double a = -model->lowerOrigin.z;
  const double b = std::hypot(model->footOrigin.x, model->footOrigin.z);
  const double lateral = model->upperOrigin.y + model->footOrigin.y;
  const double radius = std::hypot(p.y, p.z);
  const double outer = std::hypot(lateral, a + b);
  result.status = KinematicsStatus::UNREACHABLE_GEOMETRY;
  result.reachability = Reachability::UNREACHABLE;
  // Reject huge finite inputs before squaring; hypot is overflow-safe.
  if (norm(p) > outer + kDomainEpsilon ||
      radius < std::abs(lateral) - kDomainEpsilon) return result;

  const double alpha = std::atan2(p.z, p.y);
  const double hipDelta = std::acos(clamp(lateral / radius, -1.0, 1.0));
  const double phi = std::atan2(model->footOrigin.x, -model->footOrigin.z);
  double bestDistance = std::numeric_limits<double>::infinity();
  bool geometryExists = false;
  bool limitedCandidateExists = false;
  LegJointAngles accepted[4]{};

  // Two hip branches, each with two planar elbow branches. Both are required
  // even for a target generated by FK; choosing a fixed knee sign is unsound.
  for (unsigned hipBranch = 0; hipBranch < 2; ++hipBranch) {
    const double h = alpha + (hipBranch == 0 ? hipDelta : -hipDelta);
    const double v = -std::sin(h) * p.y + std::cos(h) * p.z;
    const double cosine = (p.x * p.x + v * v - a * a - b * b) / (2.0 * a * b);
    if (cosine < -1.0 - kDomainEpsilon || cosine > 1.0 + kDomainEpsilon) continue;
    geometryExists = true;
    const double elbow = std::acos(clamp(cosine, -1.0, 1.0));
    for (unsigned elbowBranch = 0; elbowBranch < 2; ++elbowBranch) {
      const double beta = elbowBranch == 0 ? elbow : -elbow;
      const double u = std::atan2(-p.x, -v) -
                       std::atan2(b * std::sin(beta), a + b * std::cos(beta));
      LegJointAngles q{};
      if (!boundedAngle(h, model->limits[0], q.hip) ||
          !boundedAngle(u, model->limits[1], q.upper) ||
          !boundedAngle(beta + phi, model->limits[2], q.lower)) continue;
      limitedCandidateExists = true;
      const FkResult fk = forwardKinematics(leg, q);
      const double residual = norm({target.x - fk.footOriginM.x,
                                    target.y - fk.footOriginM.y,
                                    target.z - fk.footOriginM.z});
      if (fk.status != KinematicsStatus::OK || !std::isfinite(residual) ||
          residual > options.toleranceM) continue;
      // At a singular branch boundary, coincident solutions count once.
      bool duplicate = false;
      for (unsigned i = 0; i < result.solutions; ++i) {
        if (std::abs(q.hip - accepted[i].hip) <= kLimitEpsilonRad &&
            std::abs(q.upper - accepted[i].upper) <= kLimitEpsilonRad &&
            std::abs(q.lower - accepted[i].lower) <= kLimitEpsilonRad) duplicate = true;
      }
      if (duplicate) continue;
      accepted[result.solutions++] = q;
      const double dh = q.hip - options.seed.hip;
      const double du = q.upper - options.seed.upper;
      const double dl = q.lower - options.seed.lower;
      const double distance = dh * dh + du * du + dl * dl;
      // Strict comparison gives a stable first-branch tie break.
      if (distance < bestDistance) {
        bestDistance = distance;
        result.joints = q;
        result.achievedFootOriginM = fk.footOriginM;
        result.residualM = residual;
      }
    }
  }
  if (result.solutions != 0) {
    result.status = KinematicsStatus::OK;
    result.reachability = Reachability::REACHABLE;
  } else if (limitedCandidateExists) {
    result.status = KinematicsStatus::NUMERICAL_FAILURE;
    result.reachability = Reachability::UNKNOWN;
  } else if (geometryExists) {
    result.status = KinematicsStatus::UNREACHABLE_LIMITS;
  }
  return result;
}

}  // namespace motion
}  // namespace matdog
