// Generated by matdog_contact_stand_export.py; DO NOT EDIT.
// Source: 09_Logs/Validation_Reports/2026-07-08_175245_C4A_offline_safe_stand_candidate.json
// Source: 09_Logs/Validation_Reports/C4_rest_to_stand_trajectory/2026-07-08_190405_C4C_contact_locked_rest_to_stand_trajectory.json
#ifndef MATDOG_MOTION_STAND_REFERENCE_DATA_H
#define MATDOG_MOTION_STAND_REFERENCE_DATA_H
#include "StandTrajectory.h"
namespace matdog { namespace motion { namespace generated {
constexpr char kC4ASha256[] = "221b6551ccf1bf36cd10b2b4136da38d1d2a73af18d65e0f3486de1faa72991b";
constexpr char kC4CSha256[] = "4b667a5995e55122b9578c39042914a373aa6bb4e0be84de11381e7f2398b7b2";
constexpr StandDefinition kStand = {
  {{0.1301352313457785, 0.094, 0.0}, {0.1301352313457785, -0.094, 0.0}, {-0.1437169534863073, -0.094, 0.0}, {-0.1437169534863073, 0.094, 0.0}},
  {{-1.8271454699690187e-08, 0.40987242488000036, 0.3495791223438952}, {1.8271454699690187e-08, 0.40987242488000036, 0.3495791223438952}, {2.7929329747154383e-08, 0.8983341577111159, 0.0007813874861022763}, {-2.7929329747154383e-08, 0.8983341577111159, 0.0007813874861022763}},
  0.1, 0.15, 51
};
} } }
#endif
